### ISSUE TITLE
Dark text on dark background is hard to read

### ISSUE THREAD

**Issue by AndydeCleyre** [darktrojan/openwith#191]
OW `7.0.3`
FF `57.0.1`
Arch Linux
Plasma desktop
dark GTK theme
FF theme "Default"

I don't think this is affecting OpenWith, but I do also have this color change in my `userChrome.css`:

```css
#nav-bar { background: #262C2E !important; border-top: #262C2E !important; }
```

Screenshot: 
![openwith](https://user-images.githubusercontent.com/1787385/33665587-6f5e0ec8-da65-11e7-914a-83864a2172e4.png)
